# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a60fc76f02a714a50bdb058497a9f7b072316f7a4ff6320c7cd614cfdf096190bcb1782f4202b6004574fcc8a5b6c74a1736fa29cc7d9570d4e453530029e18

test:
  secret_key_base: 467e088d1f98d92ab51dcd8b1e9161a7fbef171db2e1a439f1770a53dcf534d614efb26a5a13678221fc1b3161de8366e7548a1aaed6fa1d43d1b3915de46740

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
